#!/bin/bash
# LearnHub - Common Commands Reference
# Copy and paste these commands as needed

echo "🚀 LearnHub Platform - Command Reference"
echo "========================================"
echo ""
echo "📝 Copy & paste commands below:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 SETUP & INSTALLATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Navigate to project"
echo "cd c:\\Users\\ziedr\\Desktop\\sign-in-prank"
echo ""
echo "# Install dependencies"
echo "npm install"
echo ""
echo "# Create environment file from template"
echo "cp .env.example .env"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 DEVELOPMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Start development server (auto-opens browser)"
echo "npm run dev"
echo ""
echo "# Start mock API server (in another terminal)"
echo "node mock-server.js"
echo ""
echo "# Test credentials (for mock server)"
echo "Email: john@example.com | Password: password123"
echo "Email: jane@example.com | Password: password123"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏗️ BUILD & PRODUCTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Build for production (creates dist/ folder)"
echo "npm run build"
echo ""
echo "# Preview production build"
echo "npm run preview"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Clear node_modules and reinstall (if issues)"
echo "rm -rf node_modules && npm install"
echo ""
echo "# Clear npm cache"
echo "npm cache clean --force"
echo ""
echo "# Kill process on port 5173 (if port in use)"
echo "# Windows: lsof -ti:5173 | xargs kill -9"
echo "# Mac/Linux: kill -9 \$(lsof -ti:5173)"
echo ""
echo "# Check node version (requires v14+)"
echo "node --version"
echo ""
echo "# Check npm version"
echo "npm --version"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 DEPENDENCY MANAGEMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Install a new package"
echo "npm install package-name"
echo ""
echo "# Install dev dependency"
echo "npm install --save-dev package-name"
echo ""
echo "# Update all dependencies"
echo "npm update"
echo ""
echo "# List installed packages"
echo "npm list"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 BROWSER URLs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Frontend"
echo "http://localhost:5173"
echo ""
echo "# Mock API"
echo "http://localhost:3000/api"
echo "http://localhost:3000/api/health (health check)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 FILE STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "src/components/      ← React components"
echo "src/pages/          ← Page components"
echo "src/services/       ← API services"
echo "src/App.jsx         ← Main app"
echo "src/main.jsx        ← Entry point"
echo "src/index.css       ← Global styles"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "README.md              - Project overview"
echo "QUICK_REFERENCE.md     - This file"
echo "SETUP_GUIDE.md         - Installation guide"
echo "DEV_GUIDE.md          - Development guide"
echo "API_DOCUMENTATION.md  - API reference"
echo "PROJECT_SUMMARY.md    - Complete summary"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ QUICK START (Copy & Paste)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd c:\\Users\\ziedr\\Desktop\\sign-in-prank && npm install && npm run dev"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ You're All Set!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "1. npm install"
echo "2. npm run dev"
echo "3. Open http://localhost:5173"
echo ""
echo "🚀 Happy coding!"
echo ""
